### PR TITLE
[BUG] - conditionally rendered PTextFieldWrapper showCounter={false} throws TypeError: Cannot read properties of undefined (reading 'type') (issue/3364)

### LINKED ISSUE #3364: [BUG] - conditionally rendered `PTextFieldWrapper showCounter={false}` throws TypeError: Cannot read properties of undefined (reading 'type')
### JS Framework

React

### Porsche Design System version

3.15.2

### On which device(s) you can see the bug?

MacOS

### In which browsers you can see the bug?

Chrome

### Browser version

126.0.6478.63 (Offizieller Build) (arm64)

### Reproduction Example

https://stackblitz.com/edit/react-7ra9rd?file=App.tsx

### Steps to reproduce the behavior

1. Go to https://stackblitz.com/edit/react-7ra9rd?file=App.tsx
2. Open dev console
3. See error'

### Expected behavior

Conditionally/later rendered `PTextFieldWrapper showCounter={false}` does not throw error.

### Relevant log output

```
preview-b991ddc586eca.js:2 TypeError: Cannot read properties of undefined (reading 'type')
    at A.updateCounterVisibility (porsche-design-system.text-field-wrapper.93a82950505ad508f92b.js:1:9578)
    at A.onShowCounterChange (porsche-design-system.text-field-wrapper.93a82950505ad508f92b.js:1:10590)
    at porsche-design-system.v3.15.2.2af3ef8cfd80e09c3ec8.js:1:8215
    at Array.map (<anonymous>)
    at G (porsche-design-system.v3.15.2.2af3ef8cfd80e09c3ec8.js:1:8198)
    at c.set [as showCounter] (porsche-design-system.v3.15.2.2af3ef8cfd80e09c3ec8.js:1:8597)
    at eval (text-field-wrapper.wrapper.cjs:15:250)
    at Array.forEach (<anonymous>)
    at eval (text-field-wrapper.wrapper.cjs:15:206)
    at commitHookEffectListMount (react-dom.development.js:23189:26)
```

### PR DESCRIPTION
**Pull request by kaiszybiak**
### Pull Request Checklist

- [x] I have read and accept the [Contributor License Agreement](https://opensource.porsche.com/docs/cla)

#### References

- Preview: https://designsystem.porsche.com/issue/3364/

##### Problem Statement

Conditionally rendered `PTextFieldWrapper` with `showCounter={false}` throws
`TypeError: Cannot read properties of undefined (reading 'type')`

##### Analysis

The issue is not directly related to the `PTextFieldWrapper` or `showCounter={false}` prop. It also occurs for the
`PTextareaWrapper`. These components share the following characteristics:

- They use the `@Watch` decorator to call a function that requires a value assigned in `componentWillLoad()`. In this
  case, `@Watch('showCounter')` calls `updateCounterVisibility()`, which internally requires `this.input` as a
  parameter. The `this.input` value is assigned in `componentWillLoad()` via
  `this.input = getOnlyChildOfKindHTMLElementOrThrow()`.

The following conditions must be met to reproduce the error:

- The watched prop is assigned in the DOM and differs from the default value e.g. `public showCounter?: boolean = true`
  | `<PTextFieldWrapper {...props} showCounter={false}>`
- At least two components are needed, one of which will be rendered dynamically:

```tsx
// ❌ ERROR
<PTextFieldWrapper {...props} showCounter={false} description="erste component">
  <input type="password" />
</PTextFieldWrapper>;
{
  isActive && (
    <PTextFieldWrapper {...props} showCounter={false} description="zweite component">
      <input type="text" />
    </PTextFieldWrapper>
  );
}
```

```tsx
// ✅ No error if dynamically rendered component gets assigned default value
<PTextFieldWrapper {...props} showCounter={false} description="erste component">
  <input type="password" />
</PTextFieldWrapper>;
{
  isActive && (
    <PTextFieldWrapper {...props} showCounter={true} description="zweite component">
      <input type="text" />
    </PTextFieldWrapper>
  );
}
```

```tsx
// ✅ No error if both components are rendered dynamically together
{
  isActive && (
    <div>
      <PTextFieldWrapper {...props} showCounter={false} description="erste component">
        <input type="password" />
      </PTextFieldWrapper>
      ;<PTextFieldWrapper {...props} showCounter={false} description="zweite component">
        <input type="text" />
      </PTextFieldWrapper>
    </div>
  );
}
```

```tsx
// ✅ No error if not rendered dynamically
<div>
  <PTextFieldWrapper {...props} showCounter={false} description="erste component">
    <input type="password" />
  </PTextFieldWrapper>
  ;<PTextFieldWrapper {...props} showCounter={false} description="zweite component">
    <input type="text" />
  </PTextFieldWrapper>
</div>
```

In the error case, the `@Watch('showCounter')` detects a change and triggers `updateCounterVisibility()` before
`componentWillLoad()` can set `this.input = getOnlyChildOfKindHTMLElementOrThrow()`, resulting in `this.input` being
undefined. Interestingly, removing the `useBrowserLayoutEffect` in `ReactWrapperGenerator.ts ` also removes the error:

```tsx
// Removed in generated text-field-wrapper.wrapper.tsx
useBrowserLayoutEffect(() => {
  const { current } = elementRef;
  [
    'actionIcon',
    'actionLoading',
    'description',
    'hideLabel',
    'label',
    'message',
    'showCharacterCount',
    'showCounter',
    'showPasswordToggle',
    'state',
    'submitButton',
    'theme',
    'unit',
    'unitPosition',
  ].forEach((propName, i) => ((current as any)[propName] = propsToSync[i]));
}, propsToSync);
```

##### Fix

While the root cause of the issue hasn't been identified yet, a quick fix is to verify that `this.input` is defined
before calling `updateCounterVisibility()`.

#### Resolved Issue

Resolves #3364

### CODE REVIEW

File: packages/components/src/components/text-field-wrapper/text-field-wrapper.tsx [hunk 1]
```diff
@@ -145,7 +145,9 @@ export class TextFieldWrapper {
 
   @Watch('showCounter')
   public onShowCounterChange(): void {
-    this.updateCounterVisibility();
+    if (this.input) {
+      this.updateCounterVisibility();
```
Comment (stephanschroeter) [inline packages/components/src/components/text-field-wrapper/text-field-wrapper.tsx:149]: As alternative we could also adjust the function behind which causes the issue, e.g. by extending it from `export const hasCounter = (el: HTMLTextAreaElement | HTMLInputElement): boolean => el.maxLength >= 0;` to `export const hasCounter = (el: HTMLTextAreaElement | HTMLInputElement): boolean => el && el.maxLength >= 0;`

Comment (kaiszybiak) [reply packages/components/src/components/text-field-wrapper/text-field-wrapper.tsx:149]: Thanks for the suggestion. We would need to change ist as follows:

```tsx
// Before
export const hasCounterAndIsTypeText = (el: HTMLInputElement): boolean => isType(el.type, 'text') && hasCounter(el);
export const hasUnitAndIsTypeTextOrNumber = ({ type }: HTMLInputElement, unit: string): boolean => {
  return !!unit && (isType(type, 'text') || isType(type, 'number'));
};
```

```tsx
// After
export const hasCounterAndIsTypeText = (el: HTMLInputElement): boolean => el && isType(el.type, 'text') && hasCounter(el);
export const hasUnitAndIsTypeTextOrNumber = (el: HTMLInputElement, unit: string): boolean => {
  return el && !!unit && (isType(el.type, 'text') || isType(el.type, 'number'));
};
```

**Review by stephanschroeter — APPROVED** [review]
