### PR TITLE
[BUG] - Hidden Accordion content is overflowing in CSS-Grid  (Issue/3042)

### LINKED ISSUE #3042: [BUG] - Hidden Accordion content is overflowing in CSS-Grid starting at v3.12.0 (Chrome/Safari)
### Contact Details

https://porschedev.slack.com/archives/CT7AVHTTQ/p1707916918278539

### JS Framework

Components-JS

### Porsche Design System version

v3.12.0

### What browsers are you seeing the problem on?

Chrome, Safari

### Browser version

Chrome 121.0.6167.184, Safari 17.2.1 (19617.1.17.11.12)

### Reproduction Example

https://stackblitz.com/edit/vesipc?file=index.html

### Steps to reproduce the behavior

1. Go to https://stackblitz.com/edit/vesipc?file=index.html
2. Shrink the viewport to a height smaller than the form inside the accordion
3. See the scrollbar on the right, when the accordion is closed (no scrollbar should be visible)

The error is reproducible in Chrome and Safari, but not in Firefox.

It seems to have something todo with the CSS-Grid surrounding. There is a custom `grid-area` defined, when removing it, the error is gone.

### Expected behavior

There should be no scrollbar visible (the hidden content should not overflow the accordion)

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by o-hook**
### Pull Request Checklist

- [x] I have read and accept the [Contributor License Agreement](https://opensource.porsche.com/docs/cla)

#### References

- Preview: https://designsystem.porsche.com/issue/3042/

#### Scope

Short description of the pull request scope

#### Resolved Issue

Resolves #3042

### CODE REVIEW

File: packages/components/src/components/accordion/accordion-styles.ts [hunk 1]
```diff
@@ -157,6 +157,9 @@ export const getComponentCss = (
         // Necessary to make focus outlines fully visible
         padding: '4px',
         margin: '-4px',
+        // Fix scrollbar issues when slotted content includes .sr-only styles (see issue #3042)
+        transform: 'translate3d(0,0,0)',
+        zIndex: 1,
```
Comment (stephanschroeter) [inline packages/components/src/components/accordion/accordion-styles.ts:162]: Why is a `zIndex` needed to fix the overflow issue?

File: packages/components-js/tests/e2e/playwright/specs/accordion.e2e.ts [hunk 2]
```diff
@@ -65,6 +75,24 @@ test('should set "gridTemplateRows: 0fr" (0px) and "visibility: hidden" on colla
...
+    <div id="container" style="height: 200px; overflow: auto">
+      <div style="transform: translate3d(0, 0, 0)">`;
+  const otherPostMarkup = '</div></div>';
+  const otherSlottedMarkup = `
+    <div style="height: 1000px"></div>
+    <p-button>Lorem ipsum</p-button>`;
+
+  await initAccordion(page, { otherPreMarkup, otherPostMarkup, otherSlottedMarkup });
+
+  const container = (page: Page) => page.$('#container');
```
Comment (stephanschroeter) [inline packages/components-js/tests/e2e/playwright/specs/accordion.e2e.ts:89]: Isn't this good enough?

```
    const container = await page.$('#container');
    const clientHeight = await container.evaluate((el) => el.clientHeight);
    const scrollHeight = await container.evaluate((el) => el.scrollHeight);

    expect(scrollHeight > clientHeight).toBe(false);
```

File: packages/components/src/components/accordion/accordion-styles.ts (hunk 1 above)
Comment (o-hook) [reply packages/components/src/components/accordion/accordion-styles.ts:162]: Because otherwise the Accordion heading would render above overflowing content, see VRT:

Bildschirmfoto 2024-03-07 um 13 27 24

File: packages/components-js/tests/e2e/playwright/specs/accordion.e2e.ts (hunk 2 above)
Comment (o-hook) [reply packages/components-js/tests/e2e/playwright/specs/accordion.e2e.ts]: Yeah, probably 😬

**Review by stephanschroeter — APPROVED** [review]
