### PR TITLE
[BUG] Refactor parseJSONAttribute to support Safari < 16.4 (issue/3313)

### LINKED ISSUE #3313: [BUG] - Regex lookbehind in `components/src/utils/json.ts` is not supported in Safari < 16.4
### Contact Details

https://porschedev.slack.com/archives/CT7AVHTTQ/p1716889811670299

### JS Framework

Next.js

### Porsche Design System version

3.15.1

### On which device(s) you can see the bug?

iOS/Mac

### In which browsers you can see the bug?

Safari, Mobile Safari

### Browser version

< 16.4

### Reproduction Example

Download 16.2 iOS Simulator in Xcode and run the Next.js example repo (with 3.15.1 installed).
_Hint: The bug is not related to the SSR environment, it should also be broken when starting components playground._

### Steps to reproduce the behavior

Add an aria-label to any component, then the error should appear.

In Release 3.15.0 we introduced Regex lookbehinds here: https://github.com/porsche-design-system/porsche-design-system/pull/3217

This is not supported in Safari prior 16.4 => https://caniuse.com/js-regexp-lookbehind which is causing errors for one of our customers (Dealbuilder)

Bildschirmfoto 2024-05-28 um 13 57 33
Bildschirmfoto 2024-05-28 um 14 06 58

### Expected behavior

Rewrite the Regex or find another solution to achieve support of single quotes for Safari < 16.4

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by michaelworm**
### Pull Request Checklist

- [x] I have read and accept the [Contributor License Agreement](https://opensource.porsche.com/docs/cla)

#### References

- Preview: https://designsystem.porsche.com/issue/3313/

#### Scope

By avoiding using regex lookbehinds the function is working again in Safari < 16.4

#### Resolved Issue

Resolves #3313

### CODE REVIEW

**Comment by henrijoss** [comment]
Maybe we could add a console error message if the parsing failed

File: packages/components/src/utils/json.ts [hunk 1]
```diff
@@ -1,12 +1,20 @@
...
+  }
+
+  // Convert single quotes to double quotes except the ones which are escaped by backslash
+  let jsonString = attribute
+    .replace(/\\'/g, '__escaped_single_quote__')
+    .replace(/'/g, '"')
+    .replace(/__escaped_single_quote__/g, '\\\'');
+
+  // Remove string escapes except the ones followed by unicode u0027
+  jsonString = jsonString.replace(/([^\\])\\(?!u0027)/g, '$1');
```
Comment (stephanschroeter) [inline packages/components/src/utils/json.ts:14]: why can't we add the `replace` functions to where the others are and get rid of the let variable?

File: packages/components/src/utils/json.ts [hunk 2]
```diff
@@ -1,12 +1,20 @@
...
-        attribute
-          .replace(/(?<!\\)'/g, '"') // convert single quotes to double quotes except the ones which are escaped by backslash
-          .replace(/\\(?!u0027)/g, '') // remove string escapes except the ones followed by unicode u0027
-          .replace(/[\s"]?([\w-]+)[\s"]?:/g, '"$1":') // wrap keys in double quotes
-      )
-    : // input is object, e.g. { 'aria-label': 'Some label' }
-      attribute;
+  // Input is object, e.g. { 'aria-label': 'Some label' }
+  if (typeof attribute !== 'string') {
+    return attribute;
```
Comment (stephanschroeter) [inline packages/components/src/utils/json.ts:4]: Isn't a single return per function preferred over multiple returns?

File: packages/components/src/utils/json.ts (hunk 1 above)
Comment (michaelworm) [reply packages/components/src/utils/json.ts:14]: Readability, but sure we can omit the variable

File: packages/components/src/utils/json.ts (hunk 2 above)
Comment (michaelworm) [reply packages/components/src/utils/json.ts:4]: This adds alot to readability since the ternary function was complex to read and understand. Also I never heard of a single return policy for functions, but feel free to lighten me up :)

File: packages/components/src/utils/json.ts (hunk 1 above)
Comment (michaelworm) [reply packages/components/src/utils/json.ts:14]: Result (harder to read in my opinion)
```ts
return JSON.parse(
    attribute
      // Convert single quotes to double quotes except the ones which are escaped by backslash
      .replace(/\\'/g, '__escaped_single_quote__')
      .replace(/'/g, '"')
      .replace(/__escaped_single_quote__/g, '\\\'')
      // Remove string escapes except the ones followed by unicode u0027
      .replace(/([^\\])\\(?!u0027)/g, '$1')
      // Wrap keys in double quotes
      .replace(/[\s"]?([\w-]+)[\s"]?:/g, '"$1":')
  );
```

Comment (stephanschroeter) [reply packages/components/src/utils/json.ts:14]: I don't think it's more readable in this case to be honest. And I think working with `const` is always to be preferred over `let`.

Comment (michaelworm) [reply packages/components/src/utils/json.ts:14]: Okay, sure. I will push the proposed version above.

File: packages/components/src/utils/json.ts (hunk 2 above)
Comment (stephanschroeter) [reply packages/components/src/utils/json.ts:4]: I don't think there's a rule or something. I'm also fine with multiple exit points. Maybe here's an article which prefers single returns: https://stschindler.medium.com/having-only-one-return-statement-is-better-and-more-safe-5cd379b7e87c

Comment (michaelworm) [reply packages/components/src/utils/json.ts:4]: Unfortunately it's behind a "registration wall" :(

**Review by stephanschroeter — APPROVED** [review]
