### PR TITLE
Flyout, Modal dismiss button fix (issue/3558)

### LINKED ISSUE #3539: [BUG] - Dismiss Button of Flyout/Modal not sticky in case header slot is not present
### Contact Details

_No response_

### JS Framework

Vanilla JS

### Porsche Design System version

3.18.0

### On which device(s) you can see the bug?

MacBook

### In which browsers you can see the bug?

Chrome

### Browser version

_No response_

### Reproduction Example

https://stackblitz.com/edit/sqx3tl-iiay3z?file=index.html

### Steps to reproduce the behavior

1. Go to https://stackblitz.com/edit/sqx3tl-iiay3z?file=index.html
2. Click on "Open Flyout"
3. Scroll down
4. See error, dismiss button is not sticky

### Expected behavior

Dismiss Button shall stay sticky although no header slot is present.

### Notes
Same issue occurs for Modal too.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by henrijoss**
### Pull Request Checklist

- [x] I have read and accept the [Contributor License Agreement](https://opensource.porsche.com/docs/cla)

#### References

- Preview: https://designsystem.porsche.com/issue/3558

#### Scope

Short description of the pull request scope

#### Resolved Issue

Resolves #3539, #3558
Maybe also: #3422, #3569

### CODE REVIEW

File: packages/components/src/components/modal/modal-styles.ts [hunk 1]
```diff
@@ -165,6 +165,7 @@ export const getComponentCss = (
         marginBlockStart: `calc(${spacingFluidMedium} * -1)`,
         marginInlineEnd: spacingFluidSmall,
         justifySelf: 'flex-end',
+        height: 'fit-content',
```
Comment (stephanschroeter) [inline packages/components/src/components/modal/modal-styles.ts:168]:
```suggestion
        placeSelf: 'flex-start flex-end'
```

File: packages/components/src/components/flyout/flyout-styles.ts [hunk 2]
```diff
@@ -101,6 +101,7 @@ export const getComponentCss = (
       insetInlineEnd: spacingFluidSmall,
       marginBlockStart: `calc(${spacingFluidMedium} * -1)`,
       justifySelf: 'flex-end',
+      height: 'fit-content',
```
Comment (stephanschroeter) [inline packages/components/src/components/flyout/flyout-styles.ts:104]:
```suggestion
      placeSelf: 'flex-start flex-end'
```

**Review by stephanschroeter — APPROVED** [review]
