### PR TITLE
[BUG] - PSelectWrapper direction "auto" fails on initial open (Issue/2620)

### LINKED ISSUE #2620: [BUG] - PSelectWrapper direction "auto" fails on initial open
### Contact Details

_No response_

### JS Framework

React

### Porsche Design System version

3.2.0

### What browsers are you seeing the problem on?

_No response_

### Browser version

_No response_

### Reproduction Example

https://stackblitz.com/edit/react-wq4xsn?file=App.tsx

### Steps to reproduce the behaviour

1. Open StackBlitz example
2. Click on select, adjust view-height so it should not fit on bottom
3. See that it appears on bottom, although there is not enough space

### Expected behaviour

The `Select Wrapper` should determine the position / direction automatically.

### Notes
- Why isn't an automated test not covering this scenario?
- Would it be possible to reuse the positioning mechanism of Popover?

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by o-hook**
### Pull Request Checklist

- [x] I have read and accept the [Contributor License Agreement](https://opensource.porsche.com/docs/cla)

#### References

- Preview: https://designsystem.porsche.com/issue/2620/

#### Scope

Short description of the pull request scope

#### Resolved Issue

Resolves #2620

### CODE REVIEW

File: packages/components/src/components/select-wrapper/select-wrapper-dropdown/select-wrapper-dropdown-utils.ts [hunk 1]
```diff
@@ -156,6 +154,12 @@ export const getHighlightedOptionMap = (arr: OptionMap[]): OptionMap => arr.find
 export const getValidOptions = (options: OptionMap[]): OptionMap[] =>
   options.filter((item) => !item.hidden && !item.initiallyHidden && !item.disabled);
 
+export const getLengthOfVisibleOptionsAndOptgroups = (options: OptionMap[]): number => {
+  const visibleItems = options.filter((item) => !item.hidden && !item.initiallyHidden).length;
+  const itemsWithOptgroups = options.filter((item) => item.title).length;
```
Comment (denyo) [inline packages/components/src/components/select-wrapper/select-wrapper-dropdown/select-wrapper-dropdown-utils.ts:159]: Instead of filtering and iterating over all options twice, the filter conditions should be combined.  
Also with the current implementation an option is counted two times when it is not hidden and has a title?
Perhaps also rename function to something like `getAmount..`.

File: packages/components/src/components/select-wrapper/select-wrapper-dropdown/select-wrapper-dropdown-utils.spec.ts [hunk 2]
```diff
@@ -339,6 +340,21 @@ describe('getValidOptions()', () => {
   });
 });
 
+describe('getLengthOfVisibleOptionsAndOptgroups()', () => {
+  it('should return number of options that are not hidden or initiallyHidden summed with number of optgroups', () => {
```
Comment (denyo) [inline packages/components/src/components/select-wrapper/select-wrapper-dropdown/select-wrapper-dropdown-utils.spec.ts:344]: I think we need a couple of more test cases for other scenarios like the one mentioned in the other comment.

File: packages/components/src/components/select-wrapper/select-wrapper-dropdown/select-wrapper-dropdown-utils.ts (hunk 1 above)
Comment (o-hook) [reply packages/components/src/components/select-wrapper/select-wrapper-dropdown/select-wrapper-dropdown-utils.ts:159]: "Instead of filtering and iterating over all options twice, the filter conditions should be combined."
--> yes, I tried it with `reduce` but didn't get the requested results. Any idea how to simplify it?

"Also with the current implementation an option is counted two times when it is not hidden and has a title?"
--> this is intended, because every "title" should render an additional `optgroup`-like element which must be also taken into account of the height calculation.

Comment (o-hook) [reply packages/components/src/components/select-wrapper/select-wrapper-dropdown/select-wrapper-dropdown-utils.ts]: Found a solution with `reduce`. Seems to be more solid.

File: packages/components/src/components/select-wrapper/select-wrapper-dropdown/select-wrapper-dropdown-utils.ts [hunk 3]
```diff
@@ -156,6 +154,14 @@ export const getHighlightedOptionMap = (arr: OptionMap[]): OptionMap => arr.find
 export const getValidOptions = (options: OptionMap[]): OptionMap[] =>
   options.filter((item) => !item.hidden && !item.initiallyHidden && !item.disabled);
 
+export const getAmountOfVisibleOptionsAndOptgroups = (options: OptionMap[]): number => {
+  return options.reduce((count, { hidden, initiallyHidden, title }) => {
```
Comment (henrijoss) [inline packages/components/src/components/select-wrapper/select-wrapper-dropdown/select-wrapper-dropdown-utils.ts:158]: Why reduce instead of filter?

Comment (o-hook) [reply packages/components/src/components/select-wrapper/select-wrapper-dropdown/select-wrapper-dropdown-utils.ts:158]: I had used `filter`before, but it worked only with two iterations, like
```
const visibleItems = options.filter((item) => !item.hidden && !item.initiallyHidden).length;
const itemsWithOptgroups = options.filter((item) => item.title).length;
return visibleItems + itemsWithOptgroups;
  ```
Couldn't find a solution how to combine it in one iteration....

**Review by henrijoss — APPROVED** [review]

File: packages/components/src/components/select-wrapper/select-wrapper-dropdown/select-wrapper-dropdown-utils.ts (hunk 3 above)
Comment (o-hook) [reply packages/components/src/components/select-wrapper/select-wrapper-dropdown/select-wrapper-dropdown-utils.ts:158]: No, because we have to find both, all elements which are not "hidden" and additionally all elements with "title".
