### PR TITLE
[BUG] - Overlapping elements inside Accordion contents get cut off (Issue/2744)

### LINKED ISSUE #2744: [BUG] - Overlapping elements inside Accordion contents get cut off
### Contact Details

Slack: https://porschedev.slack.com/archives/CT7AVHTTQ/p1692710518112309

### JS Framework

all

### Porsche Design System version

3.5.0

### What browsers are you seeing the problem on?

all

### Browser version

all

### Reproduction Example

[Stackblitz](https://yfcmnu.stackblitz.io)

### Steps to reproduce the behavior

1. Go to [Stackblitz](https://yfcmnu.stackblitz.io)
2. Open first accordion item
3. Click select element

### Expected behavior

Select Dropdown and all other overlapping elements should not be cut off by the Accordion container.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by o-hook**
### Pull Request Checklist

- [x] I have read and accept the [Contributor License Agreement](https://opensource.porsche.com/docs/cla)

#### References

- Preview: https://designsystem.porsche.com/issue/2744/

#### Scope

Short description of the pull request scope

#### Resolved Issue

Resolves #2744

### CODE REVIEW

File: packages/components/src/components/accordion/accordion-styles.ts [hunk 1]
```diff
@@ -93,6 +93,10 @@ export const getComponentCss = (
           border: 0,
         },
       },
+      '@keyframes overflow': {
```
Comment (denyo) [inline packages/components/src/components/accordion/accordion-styles.ts:96]: Looks like this is nested within `@global`. Does it need to be there? 
I think in other cases we just have it at the bottom and not nested while referencing the animation via `$overflow`. https://cssinjs.org/jss-syntax?v=v10.10.0#keyframes-animation
