### PR TITLE
[BUG] - Tabs Bar underline disappears on tabIndex change (Issue/2674)

### LINKED ISSUE #2674: [BUG] - Tabs Bar underline disappears on tabIndex change
### Contact Details

https://porschedev.slack.com/archives/CT7AVHTTQ/p1689681933508699

### JS Framework

angular

### Porsche Design System version

`v3.5.0`

### What browsers are you seeing the problem on?

Chrome

### Browser version

_No response_

### Reproduction Example

https://stackblitz.com/edit/angular-s3t1fq?file=src%2Fapp%2Fapp.component.ts

### Steps to reproduce the behavior

1. Go to https://stackblitz.com/edit/angular-s3t1fq?file=src%2Fapp%2Fapp.component.ts
2. Change `tabIndex` to e.g. `0`
3. Wait for hot reload, see error

### Expected behavior

The active tab should be decorated with underline.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by denyo**
… tabs-bar | bh | #2674

### Pull Request Checklist

- [x] I have read and accept the [Contributor License Agreement](https://opensource.porsche.com/docs/cla)

#### References

- Preview: https://designsystem.porsche.com/issue/2674/components/tabs-bar

#### Scope

Short description of the pull request scope

#### Resolved Issue

Resolves #2674

### CODE REVIEW

File: packages/components/src/components/tabs/tabs/tabs.tsx [hunk 1]
```diff
@@ -113,23 +106,19 @@ export class Tabs {
...
+          onTabChange={(e) => e.stopPropagation()} // prevent double event emission because of identical name
         >
           {this.tabsItemElements.map((tab, index) => (
             <button key={index} type="button">
               {tab.label}
             </button>
           ))}
         </PrefixedTagNames.pTabsBar>
-        <slot onSlotchange={this.onSlotChange} />
+        <slot onSlotchange={this.defineTabsItemElements} />
```
Comment (stephanschroeter) [inline packages/components/src/components/tabs/tabs/tabs.tsx:117]: Can we use `onSlotchange` here without having the same issue like with Tabs Bar?

**Review by stephanschroeter — APPROVED** [review]
