### PR TITLE
[BUG] - Carousel: "skip-entries" link not visible on :focus-visible (Issue/3050)

### LINKED ISSUE #3050: [BUG] - Carousel: "skip-entries" link not visible on `:focus-visible`
### JS Framework

All

### Porsche Design System version

3.12.0

### Reproduction Example

https://stackblitz.com/edit/react-gitozp?file=App.tsx

### Steps to reproduce the behavior

1. Go to [Stackblitz](https://stackblitz.com/edit/react-gitozp?file=App.tsx)
2. Press Tab-Key until the prev/next buttons gets focus.
3. See error: the tab before the "prev" button focuses the "skip-entries" link but it is still hidden

### Expected behavior

The "skip-entries" link should become visible on `:focus-visible` 

### Notes

- Somehow `:focus-visible` is not getting applied on `.skip-link` although custom element should be the `activeElement`.
- Seams like Skip Link behaviour is not yet covered by test automation?

### PR DESCRIPTION
**Pull request by o-hook**
### Pull Request Checklist

- [x] I have read and accept the [Contributor License Agreement](https://opensource.porsche.com/docs/cla)

#### References

- Preview: https://designsystem.porsche.com/issue/3050/

#### Scope

Short description of the pull request scope

#### Resolved Issue

Resolves #3050

### CODE REVIEW

File: packages/components/src/components/carousel/carousel-styles.ts [hunk 1]
```diff
@@ -178,7 +178,8 @@ export const getComponentCss = (
     'skip-link': {
       opacity: 0,
       pointerEvents: 'none',
-      '&:focus-visible': {
+      // :focus mut be used in this case, because :focus-visible is just matched on the focusable element itself, not on the host element.
```
Comment (henrijoss) [inline packages/components/src/components/carousel/carousel-styles.ts:181]:
```suggestion
      // :focus must be used in this case, because :focus-visible is just matched on the focusable element itself, not on the host element.
```

File: packages/components-js/tests/e2e/puppeteer/specs/carousel.e2e.ts [hunk 2]
```diff
@@ -1141,4 +1142,15 @@ describe('accessibility', () => {
...
   });
+
+  it('should change skip-link to visible if it receives keyboard focus', async () => {
+    await initCarousel({ skipLinkTarget: '#link-after' });
+    const skipLinkHost = await getSkipLinkHost();
+
+    expect(await getElementStyle(skipLinkHost, 'opacity')).toBe('0');
+
+    await page.keyboard.press('Tab');
+
```
Comment (henrijoss) [inline packages/components-js/tests/e2e/puppeteer/specs/carousel.e2e.ts:1153]: Maybe also check that the focus is on the skip link

Comment (o-hook) [reply packages/components-js/tests/e2e/puppeteer/specs/carousel.e2e.ts:1153]: @henrijoss  Isn't this indirectly checked with the CSS selector `:focus`? Because this selector controls the opacity which then gets checked by the test.

File: packages/components/src/components/carousel/carousel-styles.ts [hunk 3]
```diff
@@ -178,7 +178,8 @@ export const getComponentCss = (
     'skip-link': {
       opacity: 0,
       pointerEvents: 'none',
-      '&:focus-visible': {
+      // :focus must be used in this case, because :focus-visible is just matched on the focusable element itself, not on the host element.
+      '&:focus': {
         opacity: 1,
         pointerEvents: 'all',
```
Comment (denyo) [inline packages/components/src/components/carousel/carousel-styles.ts:184]: Couldn't this entire part be defined the other way around without overriding/resetting?
``` 
'skip-link:not(:focus)': {
  opacity: 0,
  pointerEvents: 'none',
} 
```

File: packages/components-js/tests/e2e/puppeteer/specs/carousel.e2e.ts (hunk 2 above)
Comment (denyo) [reply packages/components-js/tests/e2e/puppeteer/specs/carousel.e2e.ts:1153]: I guess additionally checking the active element wouldn't hurt, since focus isn't explicitly covered. Currently this test would be green by having a keydown listener and adding a class or inline style on the element. 

Besides, what about the states vrts? These wrongly show the skip link button then since selectors are too greedy/wrong?

File: packages/components/src/components/carousel/carousel-styles.ts (hunk 3 above)
Comment (o-hook) [reply packages/components/src/components/carousel/carousel-styles.ts:184]: Hey @denyo : 
Do you know why the following code works but the latter not?

```
'skip-link': {
      '&:not(:focus)': {
        opacity: 0,
        pointerEvents: 'none',
      },
    },
```


```
'skip-link:not(:focus)': {
      opacity: 0,
      pointerEvents: 'none',
    },
```

File: packages/components-react/projects/react-ssr-wrapper/tests/unit/specs/__snapshots__/react-ssr-wrapper.spec.tsx.snap [hunk 4]
```diff
@@ -6771,10 +6771,6 @@ exports[`should render dsr component for PCarousel 1`] = `
 .btn {
   padding: 8px;
 }
-.skip-link {
```
Comment (stephanschroeter) [inline packages/components-react/projects/react-ssr-wrapper/tests/unit/specs/__snapshots__/react-ssr-wrapper.spec.tsx.snap:6774]: is it correct?

**Review by stephanschroeter — APPROVED** [review]
