### PR TITLE
[BUG] - Strange transition for Flyout under certain circumstances (issue/3544)

### LINKED ISSUE #3544: [BUG] - Strange transition for Flyout under certain circumstances
### Contact Details

_No response_

### JS Framework

Vanilla JS

### Porsche Design System version

3.19.0

### On which device(s) you can see the bug?

_No response_

### In which browsers you can see the bug?

Chrome

### Browser version

_No response_

### Reproduction Example

-

### Steps to reproduce the behavior

4. See error'

https://github.com/user-attachments/assets/acaaf799-01f0-4161-98c3-498c380e5141

### Expected behavior

-

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by o-hook**
### Pull Request Checklist

- [x] I have read and accept the [Contributor License Agreement](https://opensource.porsche.com/docs/cla)

#### References

- Preview: https://designsystem.porsche.com/issue/3544/

#### Scope

Short description of the pull request scope

#### Resolved Issue

Resolves #3544

### CODE REVIEW

File: packages/components/src/styles/dialog-styles.ts [hunk 1]
```diff
@@ -163,29 +166,25 @@ export const getDialogTransitionJssStyle = (isVisible: boolean, slideIn: '^' | '
       ? {
           opacity: 1,
           transform: 'initial',
+          // we need to ensure that the elements inside, which get auto focused by `.showModal()`, to always be in the
+          // viewport (or off the view on the start-hand side) before the dialog transition starts otherwise the transition
+          // won't work in all cases, e.g. `dir="rtl"` and `<p-flyout position="end" />`. Because auto focus would force the
+          // focused elements to be rendered in the viewport immediately and ignore the transition.
+          ...(applyAutoFocusHack && {
```
Comment (stephanschroeter) [inline packages/components/src/styles/dialog-styles.ts:173]: I think we don't need the auto focus hack, in case `slideIn === '^'`.

Comment (o-hook) [reply packages/components/src/styles/dialog-styles.ts]: `applyAutoFocusHack` is removed and `slide==='<'` is added instead.

File: packages/components/src/styles/dialog-styles.ts [hunk 2]
```diff
@@ -163,29 +166,25 @@ export const getDialogTransitionJssStyle = (isVisible: boolean, slideIn: '^' | '
...
+            marginInlineEnd: 0,
+          }),
         }
       : {
           opacity: 0,
+          ...(applyAutoFocusHack && {
```
[the remark this answers is not in the document]
Comment (o-hook) [reply packages/components/src/styles/dialog-styles.ts]: `applyAutoFocusHack` is removed and `slide==='<'` is added instead.

**Review by stephanschroeter — APPROVED** [review]
