### PR TITLE
[BUG] - Flyout on iOS does not respect Safari URL bar size change (issue/3123)

### LINKED ISSUE #3123: [BUG] - Flyout on iOS does not respect Safari URL bar size change
### Contact Details

https://porschedev.slack.com/archives/CT7AVHTTQ/p1710497274660849

### JS Framework

Components JS

### Porsche Design System version

latest

### What browsers are you seeing the problem on?

Mobile Safari

### Browser version

_No response_

### Reproduction Example

https://designsystem.porsche.com/latest/components/flyout/examples#slotted-header-footer-content

### Steps to reproduce the behavior

1. On iOS, go to https://designsystem.porsche.com/latest/components/flyout/examples#slotted-header-footer-content
2. Click on "Open Flyout"
3. Expand/shrink the Safari URL bar
4. See error, the flyout lies underneath the Safari URL bar leading to not visible content

https://github.com/porsche-design-system/porsche-design-system/assets/3817545/be7ada81-39ba-4f00-a794-b9ec7f16d31c

### Expected behavior

The flyout should respect the dynamic viewport height, which can be achieved using `dvh` instead of `vh`

https://caniuse.com/?search=dvh

### Notes

- Safari have fixed an CSS issue of calculating`svh` and `dvh` issues: https://developer.apple.com/documentation/safari-release-notes/safari-17_4-release-notes#Resolved-Issues

### PR DESCRIPTION
**Pull request by michaelworm**
### Pull Request Checklist

- [x] I have read and accept the [Contributor License Agreement](https://opensource.porsche.com/docs/cla)

#### References

- Preview: https://designsystem.porsche.com/issue/3123/

#### Scope

Using `dvh` instead of `vh` for the flyout dialog height resolves the issue with resizing iOS Safari URL bar as you can see in the screen record of https://designsystem.porsche.com/issue/3123/components/flyout/examples

https://github.com/porsche-design-system/porsche-design-system/assets/3817545/5652210d-c620-4c90-861a-fa7122c40012

#### Resolved Issue

Resolves #3123

### CODE REVIEW

File: packages/components/src/styles/flyout-dialog-reset-styles.ts [hunk 1]
```diff
@@ -3,8 +3,8 @@ import { JssStyle } from 'jss';
 export const getFlyoutDialogResetJssStyle = (): JssStyle => {
   return {
     position: 'fixed',
-    height: '100vh',
-    maxHeight: '100vh',
+    height: '100dvh',
```
Comment (stephanschroeter) [inline packages/components/src/styles/flyout-dialog-reset-styles.ts:6]: changelog entry is missing

File: packages/components/CHANGELOG.md [hunk 2]
```diff
@@ -18,6 +18,8 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0),
 
 - `Select`, `Multi-Select`: Cropping issues of select dropdown when used inside `Table` component
   ([#3114](https://github.com/porsche-design-system/porsche-design-system/pull/3114))
+- `Flyout`: iOS Safari URL bar overlaying
```
Comment (stephanschroeter) [inline packages/components/CHANGELOG.md:21]:
```suggestion
- `Flyout`, `Flyout Navigation`: iOS Safari URL bar overlaying
```

**Review by stephanschroeter — APPROVED** [review]
