### PR TITLE
[BUG] - Document can become scrollable on iOS although Flyout / Modal should prevent it (Issue/2798)

### LINKED ISSUE #2798: [BUG] - Document can become scrollable on iOS when Flyout / Modal should prevent it
### Contact Details

-

### JS Framework

All

### Porsche Design System version

3.7.0

### What browsers are you seeing the problem on?

Mobile Safari

### Browser version

_No response_

### Reproduction Example

-

### Steps to reproduce the behavior

4. See error'

https://github.com/porsche-design-system/porsche-design-system/assets/30120450/f07b9ce1-d904-48f7-9e6b-75578e6a360e

### Expected behavior

-

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by denyo**
### Pull Request Checklist

- [x] I have read and accept the [Contributor License Agreement](https://opensource.porsche.com/docs/cla)

#### References

- Preview: https://designsystem.porsche.com/issue/2798/

#### Scope

Short description of the pull request scope

#### Resolved Issue

Resolves #2798

### CODE REVIEW

File: packages/components/src/utils/setScrollLock.ts [hunk 1]
```diff
@@ -0,0 +1,17 @@
+export const setScrollLock = (isOpen: boolean): void => {
+  const {
+    body: { style, parentElement: htmlEl },
+  } = document;
+
+  if (isOpen) {
+    style.top = -htmlEl.scrollTop + 'px';
+    style.overflowY = 'scroll';
```
Comment (denyo) [inline packages/components/src/utils/setScrollLock.ts:8]: Not sure if this is really needed.

**Review by tatjana-gartner2 — APPROVED** [review]
