### PR TITLE
fix(storefront): form validation of select component | oh | #3204

### LINKED ISSUE #3204: [BUG] - Required p-select-wrapper does not trigger validation on blur
### Contact Details

https://porschedev.slack.com/archives/CT7AVHTTQ/p1714633084278069

### JS Framework

All

### Porsche Design System version

latest

### On which device(s) you can see the bug?

_No response_

### In which browsers you can see the bug?

_No response_

### Browser version

_No response_

### Reproduction Example

https://designsystem.porsche.com/v3/patterns/forms/example/create-account

### Steps to reproduce the behavior

1. Go to https://designsystem.porsche.com/v3/patterns/forms/example/create-account
2. Tab through the required fields without filling out
4. Error message comes up for all fields except p-select-wrapper

### Expected behavior

The p-select-wrapper should show the error message when tabbed through without selecting

### Notes

- Maybe required checkbox should also become an error state after touched + blur but not checked.
- `packages/storefront/src/pages/patterns/forms/example-create-account.vue`
- Maybe add a link on [Storefront](https://designsystem.porsche.com/v3/patterns/forms/resources#form-pattern-example-pages) to the vue examples, e.g. `https://github.com/porsche-design-system/porsche-design-system/blob/main/packages/storefront/src/pages/patterns/forms/example-create-account.vue`

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by o-hook**
### Pull Request Checklist

- [x] I have read and accept the [Contributor License Agreement](https://opensource.porsche.com/docs/cla)

#### References

- Preview: https://designsystem.porsche.com/issue/3204/patterns/forms/example/create-account

#### Scope

Short description of the pull request scope

#### Resolved Issue

Resolves #3204

### CODE REVIEW

File: packages/storefront/src/pages/patterns/forms/example-create-account.vue
Comment (henrijoss) [inline packages/storefront/src/pages/patterns/forms/example-create-account.vue:1]: Maybe better to use this vue syntax since its more common to do it like that:
- `v-bind:prop` can be replaced with the shorthand `:prop`
- `v-on:event` can be replaced with `@event`

File: packages/storefront/src/pages/patterns/forms/example-create-account.vue [hunk 1]
```diff
@@ -14,37 +14,32 @@
...
-              <p-select-wrapper :theme="storefrontTheme" label="Title">
-                <select v-bind:name="validateFieldName('title')" v-model="bag.data.title">
-                  <option value></option>
-                  <option value="option 1">Dr.</option>
-                  <option value="option 2">Prof.</option>
-                  <option value="option 3">Prof. Dr.</option>
-                </select>
-              </p-select-wrapper>
+              <p-select :theme="storefrontTheme" label="Title" v-bind:name="validateFieldName('title')">
+                <p-select-option value></p-select-option>
```
Comment (henrijoss) [inline packages/storefront/src/pages/patterns/forms/example-create-account.vue:38]:
```suggestion
                <p-select-option></p-select-option>
```

File: packages/storefront/src/pages/patterns/forms/example-create-account.vue [hunk 2]
```diff
@@ -219,6 +214,10 @@
     onFieldBlur({ target }: FocusEvent & { target: HTMLInputElement }): void {
       validateField(target.name as keyof FormModel, this.bag);
     }
+    onCustomSelectUpdate({ target }: CustomEvent & { target: HTMLElement }): void {
+      this.bag.data.salutation = (target as HTMLSelectElement).value;
+      validateField((target as HTMLSelectElement).name as keyof FormModel, this.bag);
+    }
```
Comment (henrijoss) [inline packages/storefront/src/pages/patterns/forms/example-create-account.vue:220]:
```suggestion
    onCustomSelectUpdate({ target }: CustomEvent & { target: HTMLSelectElement }): void {
      this.bag.data.salutation = target.value;
      validateField(target.name as keyof FormModel, this.bag);
    }
```

File: packages/storefront/src/pages/patterns/forms/example-create-account.vue [hunk 3]
```diff
@@ -14,53 +14,48 @@
...
-                  v-model="bag.data.salutation"
-                  v-on:change="onFieldBlur"
-                  required
-                >
-                  <option value hidden></option>
-                  <option value="Mr.">Mr.</option>
-                  <option value="Mrs.">Mrs.</option>
-                </select>
-              </p-select-wrapper>
+                <p-select-option value hidden></p-select-option>
```
Comment (henrijoss) [inline packages/storefront/src/pages/patterns/forms/example-create-account.vue:28]:
```suggestion
```
If we don't want to allow deselection is this case we can omit the option without value

File: packages/storefront/src/pages/patterns/forms/example-create-account.vue [hunk 4]
```diff
@@ -14,53 +14,48 @@
...
-                  required
-                >
-                  <option value hidden></option>
-                  <option value="Mr.">Mr.</option>
-                  <option value="Mrs.">Mrs.</option>
-                </select>
-              </p-select-wrapper>
+<p-select-option hidden></p-select-option>
+                <p-select-option value="Mr.">Mr.</p-select-option>
+                <p-select-option value="Mrs.">Mrs.</p-select-option>
```
Comment (henrijoss) [inline packages/storefront/src/pages/patterns/forms/example-create-account.vue:30]:
```suggestion
                <p-select-option hidden></p-select-option>
                <p-select-option value="Mr.">Mr.</p-select-option>
                <p-select-option value="Mrs.">Mrs.</p-select-option>
```

**Review by henrijoss — APPROVED** [review]
