### PR TITLE
[BUG] - Conditional slotted rendering of Flyout comes with strange initial transition (issue/3569)

### LINKED ISSUE #3569: [BUG] - Conditional slotted rendering of Flyout comes with strange initial transition
### Contact Details

https://porschedev.slack.com/archives/CT7AVHTTQ/p1729154038306759

### JS Framework

- React

### Porsche Design System version

- 3.18.0

### On which device(s) you can see the bug?

MacBook Pro

### In which browsers you can see the bug?

Chrome

### Browser version

130

### Reproduction Example

- https://stackblitz.com/edit/react-wefqtj-usodhz?file=App.tsx

### Steps to reproduce the behavior

1. Go to https://stackblitz.com/edit/react-wefqtj-usodhz?file=App.tsx
2. Click button
4. See error, Flyout transition does not work initially when slotted content is rendered conditional

### Expected behavior

- When slotted content of Flyout or Modal is rendered conditional the transition should work correctly initially.

### PR DESCRIPTION
**Pull request by henrijoss**
…#3569

### Pull Request Checklist

- [x] I have read and accept the [Contributor License Agreement](https://opensource.porsche.com/docs/cla)

#### References

- Preview: https://designsystem.porsche.com/issue/3569

#### Scope

Short description of the pull request scope

#### Resolved Issue

Resolves #3569

### CODE REVIEW

File: packages/components/src/components/flyout/flyout-styles.ts [hunk 1]
```diff
@@ -91,6 +107,23 @@ export const getComponentCss = (
...
+      ...(isFooterFixed &&
+        !hasSubFooter && {
+          paddingBlockEnd: 0,
+        }),
+      ...(isFooterFixed && {
+        gridTemplateRows: hasHeader ? 'min-content 1fr min-content' : '1fr',
+        '&::before': {
+          content: '""',
+          minHeight: hasHeader ? '100dvh' : `calc(100dvh - calc(${spacingFluidSmall} + ${spacingFluidMedium}))`,
+          gridRow: hasHeader ? '1 / 4' : '1 / 3',
```
Comment (stephanschroeter) [inline packages/components/src/components/flyout/flyout-styles.ts:122]: use `gridArea` instead?

File: packages/components/src/components/flyout/flyout-styles.ts [hunk 2]
```diff
@@ -91,6 +107,23 @@ export const getComponentCss = (
...
+      }),
+      ...(isFooterFixed &&
+        !hasSubFooter && {
+          paddingBlockEnd: 0,
+        }),
+      ...(isFooterFixed && {
+        gridTemplateRows: hasHeader ? 'min-content 1fr min-content' : '1fr',
+        '&::before': {
+          content: '""',
+          minHeight: hasHeader ? '100dvh' : `calc(100dvh - calc(${spacingFluidSmall} + ${spacingFluidMedium}))`,
```
Comment (stephanschroeter) [inline packages/components/src/components/flyout/flyout-styles.ts:121]: extract spacing as const and re-use where needed.

File: packages/components/src/styles/dialog-styles.ts [hunk 3]
```diff
@@ -162,19 +162,9 @@ export const getDialogTransitionJssStyle = (isVisible: boolean, slideIn: '^' | '
       ? {
           opacity: 1,
           transform: 'initial',
-          // we need to ensure that the elements inside, which get auto focused by `.showModal()`, to always be in the
-          // viewport (or off the view on the start-hand side) before the dialog transition starts otherwise the transition
-          // won't work in all cases, e.g. `dir="rtl"` and `<p-flyout position="end" />`. Because auto focus would force the
-          // focused elements to be rendered in the viewport immediately and ignore the transition.
-          ...(slideIn === '<' && {
-            marginInlineEnd: 0,
```
Comment (stephanschroeter) [inline packages/components/src/styles/dialog-styles.ts:170]: adjust transition itself too.

**Review by stephanschroeter — APPROVED** [review]

**Review by stephanschroeter — APPROVED** [review]

**Review by stephanschroeter — APPROVED** [review]
